### ISSUE TITLE
Configure Amazon time sync service on ECS cluster nodes

### ISSUE THREAD

**Issue by hectcastro** [azavea/terraform-aws-ecs-cluster#25]
In the `cloud-config` for ECS cluster nodes, ensure that a NTP configuration using the internal Amazon time sync service IP persists.

Prefer using `chrony`, if possible.

See:

- http://cloudinit.readthedocs.io/en/latest/topics/modules.html#ntp
- https://aws.amazon.com/blogs/aws/keeping-time-with-amazon-time-sync-service/

**Comment by rbreslow** [comment]
The latest Amazon Linux AMI uses cloud-init `0.7.6` and support for the NTP module [wasn't added until](https://github.com/number5/cloud-init/blob/bbcc5e82e6c8e87ca483150205127cb0436c4cd9/ChangeLog#L717) `0.7.8`. 

However, I found that the latest Amazon Linux AMI `amzn-ami-2018.03.a-amazon-ecs-optimized (ami-5253c32d)` has NTP already configured for the Amazon Time Sync service. 

```bash
# Use and prefer the Amazon Time Service server
server 169.254.169.123 prefer iburst minpoll 3
```

This issue was created as follow up to an incident where a clock skew on an EC2 instance prevented new ECS tasks from starting to serve new requests.

>Low priority/medium impact: Regularly sync system time on long-running EC2 instances to avoid the clock drift issue, either via the AWS Time Sync Service or NTP

To see if the NTP configuration noted was not present in the EC2 instance, I ran a diff between `ntp.conf` from the AMI that was on the EC2 instance `amzn-ami-2016.09.f-amazon-ecs-optimized (ami-b2df2ca4)` and the latest Amazon Linux AMI.

```diff
diff --git a/ntp_old.conf b/ntp.conf
index 2ee2fbb..37a50fa 100644
--- a/ntp_old.conf
+++ b/ntp.conf
@@ -1,11 +1,14 @@
-# For more information about this file, see the man pages
-# ntp.conf(5), ntp_acc(5), ntp_auth(5), ntp_clock(5), ntp_misc(5), ntp_mon(5).
+# For more information about this file, see the ntp.conf(5) man page.

+# Record the frequency of the system clock.
 driftfile /var/lib/ntp/drift

 # Permit time synchronization with our time source, but do not
 # permit the source to query or modify the service on this system.
-restrict default nomodify notrap nopeer noquery
+restrict default nomodify notrap nopeer noepeer noquery
+
+# Permit association with pool servers.
+restrict source nomodify notrap noepeer noquery

 # Permit all access over the loopback interface.  This could
 # be tightened as well, but to do so would effect some of
@@ -16,19 +19,15 @@ restrict ::1
 # Hosts on local network are less restricted.
 #restrict 192.168.1.0 mask 255.255.255.0 nomodify notrap

+# Use and prefer the Amazon Time Service server
+server 169.254.169.123 prefer iburst minpoll 3
+
 # Use public servers from the pool.ntp.org project.
 # Please consider joining the pool (http://www.pool.ntp.org/join.html).
-server 0.amazon.pool.ntp.org iburst
-server 1.amazon.pool.ntp.org iburst
-server 2.amazon.pool.ntp.org iburst
-server 3.amazon.pool.ntp.org iburst
-
-#broadcast 192.168.1.255 autokey    # broadcast server
-#broadcastclient            # broadcast client
-#broadcast 224.0.1.1 autokey        # multicast server
-#multicastclient 224.0.1.1        # multicast client
-#manycastserver 239.255.254.254        # manycast server
-#manycastclient 239.255.254.254 autokey # manycast client
+pool 2.amazon.pool.ntp.org iburst
+
+# Reduce the maximum number of servers used from the pool.
+tos maxclock 5

 # Enable public key cryptography.
 #crypto
```

Until ECS with Amazon Linux 2 (and `chrony` preconfigured) goes GA, this may have the potential to resolve our issue.
