### ISSUE TITLE
Migrate to using aws_launch_template vs. aws_launch_configuration

### ISSUE THREAD

**Issue by hectcastro** [azavea/terraform-aws-ecs-cluster#30]
Looks like this is the new way to provide instance level parameters for ASGs. After a quick review, it appears that all of the arguments we're currently providing to `aws_launch_configuration` are supported by `aws_launch_template` (`block_device_mappings` looks like the only one that isn't straightforward).

The motivation for migrating to `aws_launch_template` is to support enabling T2 Unlimited support via `credit_specification`.

See: https://www.terraform.io/docs/providers/aws/r/launch_template.html

**Comment by hectcastro** [comment]
Unblocked by https://github.com/terraform-providers/terraform-provider-aws/pull/5632, which is in v1.34.0+ of the AWS Terraform provider.

**Comment by rbreslow** [comment]
* [ ] Merge https://github.com/azavea/terraform-aws-ecs-cluster/pull/34
* [x] Merge https://github.com/azavea/terraform-aws-ecs-cluster/pull/37
* [ ] Cut a release on [terraform-aws-ecs-cluster](https://github.com/azavea/terraform-aws-ecs-cluster)

I feel like I'm missing something. I believe there was another Terraform module we wanted to cut a release on in tandem with merging this change.

Also, with https://github.com/azavea/terraform-aws-ecs-cluster/pull/34, I believe we paired and setup testing environments out-of-band, which is why the testing instructions were left unfinished. I am going to test again and I will update the PR body.

**Comment by hectcastro** [comment]
I don't think that we have to bundle the issues referenced with this one.

I think that the two modules we wanted to release in tandem was this and `terraform-aws-ecs-web-service`. That was for the autoscaling role ARN removal, but we already did that.

I updated the status of this issue, but it isn't in our current sprint yet, so I would hold off on updating the PR until we add it to a sprint.
