### ISSUE TITLE
Clarification on CPUReservation

### ISSUE THREAD

**Issue by pessoa** [azavea/terraform-aws-ecs-cluster#35]
Why is the CPUReservation metric in use for the aws_cloudwatch_metric_alarm? Shouldn't it be instead CPUUtilization? Or allow configuration of either?

From https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cloudwatch-metrics.html we see that CPUReservation is only different than 0 when you actually reserve CPU for the tasks.
If you launch a set of non CPU limited tasks you will want to scale up or down based on actual CPUUtilization.

**Comment by hectcastro** [comment]
Sure. We use `CPUReservation` because that helps us best determine if a cluster no longer has enough CPU (or memory when we use that metric) to place a given task. We make sure that each task definition defines its CPU and memory requirements based on what it needs to operate.

We use metrics like `CPUUtilization` to scale the ECS services themselves. As those scale up and down, the cluster reservation metrics change to trigger the alarms in this module.

**Comment by pessoa** [comment]
Thanks! I've not see where CPUUtilization is used. Can you point me to it please?

**Comment by hectcastro** [comment]
Sure. An example showing how to scale ECS services with `CPUUtilization` can be found here: https://github.com/azavea/terraform-aws-ecs-web-service#usage
